chore: bump Go to version 1.21
open-feature/go-sdk pull request #255
Opened 2024-02-13 14:11 UTC by odubajDT

2024-02-13 16:47 UTC, Kavindu-Dodan commented
My concern here is the version jump from 1.19 to 1.21. Given SDK is a central piece of OF, I think we should move step-wise (1.19 -> 1.20 -> 1.21) so that adaptation becomes easier where needed. We have a tracking issue for 1.20 already - https://github.com/open-feature/go-sdk/issues/253

2024-02-23 21:08 UTC, Kavindu-Dodan approved these changes

2024-02-23 21:10 UTC, Kavindu-Dodan commented
I have upgraded the PR to bump Go version to 1.20. This allows us to upgrade SDK's go version linearly, avoiding unnecessary impact on downstream users.

2024-03-28 15:47 UTC, Kavindu-Dodan requested changes
Pending for TC decision on runtime support & documentation

2024-04-09 17:15 UTC, toddbaert commented
After our meeting I'm sure I can say the TC will not block dropping Go 1.19, as long as the go-maintainers support that.

Go is a particularly fast-moving runtime.

2024-04-09 17:15 UTC, toddbaert approved these changes

2024-04-09 17:19 UTC, Kavindu-Dodan approved these changes

2024-04-09 17:29 UTC, lukas-reining approved these changes

2024-04-09 17:44 UTC, beeme1mr commented
Can we extend the readme to include a section on our support policy?

2024-04-09 19:43 UTC, Kavindu-Dodan commented
> Can we extend the readme to include a section on our support policy?

I tried to add this with this commit - https://github.com/open-feature/go-sdk/pull/255/commits/f854ec49213e6c980c35e0f77eafb31813db9f73

2024-04-09 19:47 UTC, beeme1mr commented on README.md
> +> OpenFeature Go SDK attempts to support currently maintained Go language version.
```suggestion
> The OpenFeature Go SDK only supports currently maintained Go language versions.
```

2024-04-09 20:13 UTC, beeme1mr approved these changes

2024-04-09 20:15 UTC, merged